### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Tamiflu233** [QiSun123/GenRDK#1]
I'd like to know where your code is used for Consistency guided Knowledge Denoising. also I want to know how to use LLama to train for DocRE tasks as I noticed that your data format is the same as DocRED.Can you provide you code for training?Thx a lot.

**Comment by QiSun123** [comment]
Thanks for your question. I use llama2-13b-chat and finetune (LoRA) it with our synthetic data. The format is according to the alpaca format which can also be found in paper. We follow the official llama2 code (https://github.com/meta-llama/llama-recipes) to finetune  llama2-13b-chat with LoRA.

**Comment by QiSun123** [comment]
For the consistency-guided knowledge denoising part, refer to denoise.py. We have also upload the code for converting DocRED format data into alpaca format. Hope this can help you.
