### ISSUE TITLE
作者真的有计划放出完整代码吗？Does the author really plan to release the complete code?

### ISSUE THREAD

**Issue by Winson-Huang** [QiSun123/GenRDK#2]

**Comment by QiSun123** [comment]
Thanks for your question. The most important code has been released, and the remaining trivial code is still being organized. All technical details required for reproduction have been disclosed in the paper. If you urgently need to use this code, please contact us by email and indicate your identity and purpose. We are very willing to provide assistance.

**Comment by Winson-Huang** [comment]
I really don't think you provided all technical details required for reproduction in the paper. In table 1 you introduce your algorithm which contains 10 steps, but the prompts' detail and training methods in step#2, #3, #8, #9, #10 are not so clear.

**Comment by QiSun123** [comment]
Our training prompt follows the alpaca format, the fine-tune method is LoRA which is shown in Figure 3 of our paper. This part code follows the official code (https://github.com/meta-llama/llama-recipes). You can see it for more training details. To further clarify our method, we have provided additional details in our code, which may be helpful to you.
